/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Message {
  'id' : MessageId,
  'content' : string,
  'timestamp' : Timestamp,
}
export type MessageId = bigint;
export interface Template {
  'id' : TemplateId,
  'name' : string,
  'text' : string,
}
export type TemplateId = bigint;
export type Timestamp = bigint;
export interface _SERVICE {
  'createTemplate' : ActorMethod<[string, string], Template>,
  'deleteMessage' : ActorMethod<[MessageId], boolean>,
  'deleteTemplate' : ActorMethod<[TemplateId], boolean>,
  'listMessages' : ActorMethod<[], Array<Message>>,
  'listTemplates' : ActorMethod<[], Array<Template>>,
  'sendMessage' : ActorMethod<[string], Message>,
  'updateTemplate' : ActorMethod<[TemplateId, string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];