/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TemplateId = IDL.Nat;
export const Template = IDL.Record({
  'id' : TemplateId,
  'name' : IDL.Text,
  'text' : IDL.Text,
});
export const MessageId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Message = IDL.Record({
  'id' : MessageId,
  'content' : IDL.Text,
  'timestamp' : Timestamp,
});

export const idlService = IDL.Service({
  'createTemplate' : IDL.Func([IDL.Text, IDL.Text], [Template], []),
  'deleteMessage' : IDL.Func([MessageId], [IDL.Bool], []),
  'deleteTemplate' : IDL.Func([TemplateId], [IDL.Bool], []),
  'listMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'listTemplates' : IDL.Func([], [IDL.Vec(Template)], ['query']),
  'sendMessage' : IDL.Func([IDL.Text], [Message], []),
  'updateTemplate' : IDL.Func([TemplateId, IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TemplateId = IDL.Nat;
  const Template = IDL.Record({
    'id' : TemplateId,
    'name' : IDL.Text,
    'text' : IDL.Text,
  });
  const MessageId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Message = IDL.Record({
    'id' : MessageId,
    'content' : IDL.Text,
    'timestamp' : Timestamp,
  });
  
  return IDL.Service({
    'createTemplate' : IDL.Func([IDL.Text, IDL.Text], [Template], []),
    'deleteMessage' : IDL.Func([MessageId], [IDL.Bool], []),
    'deleteTemplate' : IDL.Func([TemplateId], [IDL.Bool], []),
    'listMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'listTemplates' : IDL.Func([], [IDL.Vec(Template)], ['query']),
    'sendMessage' : IDL.Func([IDL.Text], [Message], []),
    'updateTemplate' : IDL.Func(
        [TemplateId, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };